language: node_js
node_js:
  - "6"
  - "8"
  - "10"
addons:
  apt:
    packages:
      - libargon2-0-dev
      - lcov
    sources:
      - sourceline: 'ppa:angelsl/trusty-crypto-backports'
env:
  - npm_config_debug=yes
before_install: npm install -g node-gyp nyc
script: nyc npm test && npm run test-ts
after_success:
  - nyc report --reporter=text-lcov > lcov-js.info
  - lcov -c -d . --no-external -o lcov-cpp.info
  - lcov -r lcov-cpp.info "*/node_modules/*" -o lcov-cpp.info
  - lcov -a lcov-cpp.info -a lcov-js.info -o lcov.info
  - npm install -g coveralls && coveralls < lcov.info
